e_invoice.settings:
  type: config_object
  label: 'E-Invoice settings'
  mapping:
    invoice_provider:
      type: string
      label: 'Invoice provider'
    invoice_host:
      type: string
      label: 'Host url'
    invoice_username:
      type: string
      label: 'Username'
    invoice_password:
      type: string
      label: 'Password'
    invoice_taxcode:
      type: string
      label: 'Tax code'
    invoice_appid:
      type: string
      label: 'App id'
    invoice_token:
      type: string
      label: 'Token'
    invoice_templates:
      type: sequence
      label: 'Templates'
      sequence:
        type: mapping
        label: 'Template'
        mapping:
          pattern:
            type: string
            label: 'Pattern'
          serial:
            type: string
            label: 'Serial'