e_invoice.settings:
  type: config_object
  label: 'E-Invoice settings'
  mapping:
    invoice_provider:
      type: string
      label: 'Provider'
    invoice_host:
      type: string
      label: 'Host'
    invoice_username:
      type: string
      label: 'Username'
    invoice_password:
      type: string
      label: 'Password'
    invoice_taxcode:
      type: string
      label: 'Tax code'
    invoice_appid:
      type: string
      label: 'App ID'
    invoice_appurl:
      type: string
      label: 'App URL'
    invoice_client:
      type: string
      label: 'Client ID'
    invoice_token:
      type: string
      label: 'Token'
    invoice_jwt_token:
      type: string
      label: 'JWT Token'
    invoice_subscribers:
      type: string
      label: 'Subscribers'
    invoice_organization:
      type: string
      label: 'Organization'
    invoice_expiration:
      type: date
      label: 'Expiration'
    invoice_templates:
      type: sequence
      label: 'Templates'
      sequence:
        type: mapping
        label: 'Template'
        mapping:
          pattern:
            type: string
            label: 'Pattern'
          serial:
            type: string
            label: 'Serial'